name: ai-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=26.1.2
  - setuptools=81.0.0
  - pip:
      - torch==2.11.0
      - torchvision==0.26.0
      - torchaudio==2.11.0
      - numpy==2.2.6
      - pandas==2.3.3
      - scipy==1.15.3
      - scikit-learn==1.7.2
      - ultralytics==8.4.91
      - SoccerNet==0.1.62
